/**
 * Type-level collision guards for provider runtime extensions.
 *
 * @module
 */

type KnownPropertyKey<TKey> = TKey extends string
  ? string extends TKey
    ? never
    : TKey
  : TKey extends number
    ? number extends TKey
      ? never
      : TKey
    : TKey extends symbol
      ? symbol extends TKey
        ? never
        : TKey
      : never

type KnownKeys<T> = KnownPropertyKey<keyof T>

/**
 * Context passed to a provider runtime extension factory.
 *
 * Extensions are for provider-specific capabilities that should travel
 * beside generation, such as embeddings or reranking. They do not change
 * the Crux generation runtime itself.
 */
export interface ProviderRuntimeExtensionContext<TClient, TRuntime> {
  /** Stable provider runtime id. */
  readonly id: string
  /** Client value originally passed to `create()`. */
  readonly client: TClient
  /** Core-compiled generation runtime for this provider. */
  readonly runtime: TRuntime
}

/**
 * Extension keys that would collide with members already generated by core.
 *
 * The check intentionally uses known literal keys. Broad index signatures are
 * still protected by the runtime collision guard, while normal object-literal
 * extension factories get immediate feedback in TypeScript.
 */
export type ProviderRuntimeExtensionCollisionKeys<TRuntime, TExtensions extends object> = Extract<
  KnownKeys<TExtensions>,
  keyof TRuntime
>

/**
 * Provider-specific capabilities attached beside the generated runtime.
 *
 * Extension objects keep their flat public shape, e.g. `runtime.embedding()`,
 * but known keys that overlap with core runtime members such as `generate`,
 * `stream`, or `executorId` resolve to `never` so adapter authors get a
 * compile-time error before `create()` runs.
 */
export type ProviderRuntimeExtension<TRuntime, TExtensions extends object> = TExtensions & {
  readonly [K in ProviderRuntimeExtensionCollisionKeys<TRuntime, TExtensions>]: never
}

/**
 * Creates provider-specific extensions beside the generation runtime.
 *
 * Use this for capabilities that share the provider client but do not replace
 * Crux-owned generation behavior, such as embeddings or rerankers.
 */
export type ProviderRuntimeExtender<TClient, TRuntime, TExtensions extends object> = (
  ctx: ProviderRuntimeExtensionContext<TClient, TRuntime>,
) => ProviderRuntimeExtension<TRuntime, TExtensions>
