/**
 * Shared provider-runtime factory helpers.
 *
 * @internal
 * @module
 */

import type { DefinedProviderRuntime, ProviderRuntimeDepsArg } from './types'

/**
 * Create the frozen public runtime wrapper around a concrete runtime factory.
 *
 * Provider-specific extensions are evaluated after the generated runtime is
 * bound to a client, so extension factories can share the same SDK client
 * without replacing Crux-owned generation methods.
 */
export function createDefinedProviderRuntime<
  TClient,
  TModel,
  TRawResponse,
  TRawStream,
  TExtra extends Record<string, unknown>,
  TDeps extends Record<string, unknown>,
  TRuntime extends object,
  TExtensions extends object,
>(
  id: string,
  createRuntime: (client: TClient, ...depsArg: ProviderRuntimeDepsArg<TDeps>) => TRuntime,
  extend:
    | ((ctx: { readonly id: string; readonly client: TClient; readonly runtime: TRuntime }) => TExtensions)
    | undefined,
): DefinedProviderRuntime<TClient, TModel, TRawResponse, TRawStream, TExtra, TDeps, TRuntime, TExtensions> {
  return Object.freeze({
    id,
    create(client: TClient, ...depsArg: ProviderRuntimeDepsArg<TDeps>) {
      const runtime = createRuntime(client, ...depsArg)
      if (!extend) return runtime as TRuntime & TExtensions

      return mergeRuntimeExtensions(id, runtime, extend({ id, client, runtime })) as TRuntime & TExtensions
    },
  })
}

/**
 * Merge provider-specific extensions without allowing them to replace the
 * Crux-owned runtime contract generated by core.
 */
function mergeRuntimeExtensions<TRuntime extends object, TExtensions extends object>(
  id: string,
  runtime: TRuntime,
  extensions: TExtensions,
): TRuntime & TExtensions {
  for (const key of Reflect.ownKeys(extensions)) {
    if (
      Object.prototype.propertyIsEnumerable.call(extensions, key) &&
      Object.prototype.hasOwnProperty.call(runtime, key)
    ) {
      throw new Error(`Provider runtime "${id}" extension cannot replace generated runtime key "${String(key)}".`)
    }
  }

  return Object.freeze({
    ...runtime,
    ...extensions,
  }) as TRuntime & TExtensions
}
