[workspace]
members = [
    "crates/protocol",
    "crates/syntax-oxc",
    "crates/facts",
    "crates/primitives",
    "crates/lints",
    "crates/static-compiler",
    "crates/worker",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.93"
license = "Apache-2.0"
repository = "https://github.com/use-crux/crux.git"

[workspace.dependencies]
crux-indexer-protocol = { path = "crates/protocol" }
crux-indexer-syntax-oxc = { path = "crates/syntax-oxc" }
crux-indexer-facts = { path = "crates/facts" }
crux-indexer-primitives = { path = "crates/primitives" }
crux-indexer-lints = { path = "crates/lints" }
crux-indexer-static-compiler = { path = "crates/static-compiler" }
oxc_allocator = "0.133.0"
oxc_ast = "0.133.0"
oxc_parser = "0.133.0"
oxc_span = "0.133.0"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
