packages:
  - "apps/*"
  - "examples/*"
  - "packages/*"
  - "packages/local/npm/*"
linkWorkspacePackages: true
sharedWorkspaceLockfile: true
allowBuilds:
  '@embedded-postgres/darwin-arm64': true
  '@embedded-postgres/darwin-x64': true
  '@embedded-postgres/linux-arm': true
  '@embedded-postgres/linux-arm64': true
  '@embedded-postgres/linux-ia32': true
  '@embedded-postgres/linux-ppc64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/windows-x64': true
  '@google/genai': true
  core-js: false
  esbuild: true
  protobufjs: true
  sharp: true
