const firstPartySemanticCallNames = [
  'Agent',
  'agent',
  'blackboard',
  'cascade',
  'consensus',
  'constraint',
  'convexAgent',
  'createTool',
  'cruxFlow',
  'evaluate',
  'fallback',
  'flow',
  'fromRegistry',
  'guardrail',
  'injectable',
  'llmJudge',
  'match',
  'memory',
  'parallel',
  'pipeline',
  'registry',
  'retrievalPipeline',
  'retriever',
  'router',
  'swarm',
  'tool',
  'context',
  'prompt',
  'when',
  'workspace',
] as const

/** Sorted first-party call names that make a source file semantically relevant. */
export const semanticPrimitiveCallNames = [...new Set(firstPartySemanticCallNames)].sort()
