import {
  injectableContributionRelationPolicies,
  injectableUseRelationPolicies,
  invocationAccessRelationPolicies,
  mediaRelationPolicies,
  mcpRelationPolicies,
  promptContextAccessRelationPolicies,
  routingTargetRelationPolicies,
  workspaceSnapshotAccessRelationPolicies,
} from './policy-groups'
import type { IndexRelationPolicy } from './types'

export const indexRelationPolicies = [
  ...injectableUseRelationPolicies,
  ...injectableContributionRelationPolicies,
  ...promptContextAccessRelationPolicies,
  ...workspaceSnapshotAccessRelationPolicies,
  ...mediaRelationPolicies,
  ...mcpRelationPolicies,
  {
    type: 'defer.contained_by',
    fromKinds: ['deferred-work'],
    toKinds: ['prompt', 'tool', 'agent', 'flow', 'flow.step'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'defer.targets_task',
    fromKinds: ['deferred-work'],
    toKinds: ['task'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.uses_prompt',
    fromKinds: ['agent'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.uses_thread',
    fromKinds: ['agent'],
    toKinds: ['thread'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'signal.provider.uses_transport',
    fromKinds: ['signal.provider'],
    toKinds: ['signal.transport'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'signal.provider.publishes_signal',
    fromKinds: ['signal.provider'],
    toKinds: ['signal'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'signal.transportBinding.binds_provider',
    fromKinds: ['signal.transportBinding'],
    toKinds: ['signal.provider'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'signal.transportBinding.targets_signal',
    fromKinds: ['signal.transportBinding'],
    toKinds: ['signal'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'session.targets_agent',
    fromKinds: ['session'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: false,
    runtimeJoin: true,
  },
  {
    type: 'session.targets_flow',
    fromKinds: ['session'],
    toKinds: ['flow'],
    presentation: 'both',
    partial: false,
    runtimeJoin: true,
  },
  {
    type: 'session.subscribes_to_signal',
    fromKinds: ['session'],
    toKinds: ['signal'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.uses_tool',
    fromKinds: ['agent'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.can_handoff_to',
    fromKinds: ['agent'],
    toKinds: ['agent'],
    presentation: 'edge',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.reads_memory',
    fromKinds: ['agent'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.writes_memory',
    fromKinds: ['agent'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.reads_blackboard',
    fromKinds: ['agent'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.writes_blackboard',
    fromKinds: ['agent'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.reads_workspace',
    fromKinds: ['agent'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.writes_workspace',
    fromKinds: ['agent'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.reads_memory',
    fromKinds: ['tool'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.writes_memory',
    fromKinds: ['tool'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.reads_blackboard',
    fromKinds: ['tool'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.writes_blackboard',
    fromKinds: ['tool'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.reads_workspace',
    fromKinds: ['tool'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.writes_workspace',
    fromKinds: ['tool'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'skill.uses_registry',
    fromKinds: ['skill'],
    toKinds: ['registry'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.knowledgeBase.uses_communities',
    fromKinds: ['rag.knowledgeBase'],
    toKinds: ['knowledge.communities'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.knowledgeBase.includes_view',
    fromKinds: ['rag.knowledgeBase'],
    toKinds: ['rag.knowledgeBase.view'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'knowledge.relation.uses_model',
    fromKinds: ['knowledge.relation'],
    toKinds: ['knowledge.model'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'knowledge.assertions.uses_model',
    fromKinds: ['knowledge.assertions'],
    toKinds: ['knowledge.model'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'knowledge.communities.uses_model',
    fromKinds: ['knowledge.communities'],
    toKinds: ['knowledge.model'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'flow.includes_step',
    fromKinds: ['flow'],
    toKinds: ['flow.step'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_prompt',
    fromKinds: ['flow.step'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_agent',
    fromKinds: ['flow.step'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_tool',
    fromKinds: ['flow.step'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_memory',
    fromKinds: ['flow.step'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_blackboard',
    fromKinds: ['flow.step'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.reads_memory',
    fromKinds: ['flow.step'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.writes_memory',
    fromKinds: ['flow.step'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.reads_blackboard',
    fromKinds: ['flow.step'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.writes_blackboard',
    fromKinds: ['flow.step'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.reads_workspace',
    fromKinds: ['flow.step'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.writes_workspace',
    fromKinds: ['flow.step'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.waits_for_signal',
    fromKinds: ['flow.step'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  ...invocationAccessRelationPolicies,
  ...routingTargetRelationPolicies,
  {
    type: 'composition.uses_agent',
    fromKinds: [
      'composition.parallel',
      'composition.pipeline',
      'composition.swarm',
      'composition.consensus',
    ],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'composition.uses_flow',
    fromKinds: [
      'composition.parallel',
      'composition.pipeline',
      'composition.swarm',
      'composition.consensus',
    ],
    toKinds: ['flow'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'composition.uses_prompt',
    fromKinds: [
      'composition.parallel',
      'composition.pipeline',
      'composition.swarm',
      'composition.consensus',
    ],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'composition.uses_tool',
    fromKinds: [
      'composition.parallel',
      'composition.pipeline',
      'composition.swarm',
      'composition.consensus',
    ],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.includes_branch',
    fromKinds: ['composition.parallel'],
    toKinds: ['composition.parallel.branch'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.branch.uses_agent',
    fromKinds: ['composition.parallel.branch'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.branch.uses_flow',
    fromKinds: ['composition.parallel.branch'],
    toKinds: ['flow'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.branch.uses_prompt',
    fromKinds: ['composition.parallel.branch'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.branch.uses_tool',
    fromKinds: ['composition.parallel.branch'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.includes_stage',
    fromKinds: ['composition.pipeline'],
    toKinds: ['composition.pipeline.stage'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.stage.uses_agent',
    fromKinds: ['composition.pipeline.stage'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.stage.uses_flow',
    fromKinds: ['composition.pipeline.stage'],
    toKinds: ['flow'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.stage.uses_prompt',
    fromKinds: ['composition.pipeline.stage'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.stage.uses_tool',
    fromKinds: ['composition.pipeline.stage'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'consensus.includes_agent',
    fromKinds: ['composition.consensus'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'consensus.uses_judge',
    fromKinds: ['composition.consensus'],
    toKinds: ['agent', 'scorer'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'consensus.uses_scorer',
    fromKinds: ['composition.consensus'],
    toKinds: ['scorer'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'swarm.includes_agent',
    fromKinds: ['composition.swarm'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'swarm.coordinated_by',
    fromKinds: ['composition.swarm'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'swarm.uses_blackboard',
    fromKinds: ['composition.swarm'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'swarm.uses_memory',
    fromKinds: ['composition.swarm'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.recipe.uses_retriever',
    fromKinds: ['rag.recipe'],
    toKinds: ['rag.retriever'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.recipe.includes_step',
    fromKinds: ['rag.recipe'],
    toKinds: ['rag.recipe.step'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.recipe.step.uses_retriever',
    fromKinds: ['rag.recipe.step'],
    toKinds: ['rag.retriever'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.recipe.step.uses_scorer',
    fromKinds: ['rag.recipe.step'],
    toKinds: ['scorer'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.recipe.step.uses_reranker',
    fromKinds: ['rag.recipe.step'],
    toKinds: ['rag.reranker'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.pipeline.uses_retriever',
    fromKinds: ['rag.pipeline'],
    toKinds: ['rag.retriever'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.pipeline.includes_stage',
    fromKinds: ['rag.pipeline'],
    toKinds: ['rag.pipeline.stage'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.pipeline.stage.uses_retriever',
    fromKinds: ['rag.pipeline.stage'],
    toKinds: ['rag.retriever'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.pipeline.stage.uses_scorer',
    fromKinds: ['rag.pipeline.stage'],
    toKinds: ['scorer'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.retriever.uses_storage',
    fromKinds: ['rag.retriever'],
    toKinds: ['storage.bundle', 'storage.scope'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.retriever.uses_record_store',
    fromKinds: ['rag.retriever'],
    toKinds: ['storage.recordStore'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.retriever.uses_search_store',
    fromKinds: ['rag.retriever'],
    toKinds: ['storage.searchStore'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.retriever.uses_asset_store',
    fromKinds: ['rag.retriever'],
    toKinds: ['storage.assetStore'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'embedding.call.uses_embedding',
    fromKinds: ['embedding.call'],
    toKinds: ['embedding'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.indexer.uses_dense_embedding',
    fromKinds: ['rag.indexer'],
    toKinds: ['embedding'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.indexer.uses_sparse_embedding',
    fromKinds: ['rag.indexer'],
    toKinds: ['embedding'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.retriever.uses_dense_embedding',
    fromKinds: ['rag.retriever'],
    toKinds: ['embedding'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.retriever.uses_sparse_embedding',
    fromKinds: ['rag.retriever'],
    toKinds: ['embedding'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.knowledgeBase.uses_dense_embedding',
    fromKinds: ['rag.knowledgeBase'],
    toKinds: ['embedding'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'rag.knowledgeBase.uses_sparse_embedding',
    fromKinds: ['rag.knowledgeBase'],
    toKinds: ['embedding'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'memory.includes_block',
    fromKinds: ['memory'],
    toKinds: ['memory.block'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'memory.uses_store',
    fromKinds: ['memory'],
    toKinds: ['memory.store'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'blackboard.uses_store',
    fromKinds: ['blackboard'],
    toKinds: ['memory.store'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'blackboard.uses_schema',
    fromKinds: ['blackboard'],
    presentation: 'detail',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'workspace.exposes_tool',
    fromKinds: ['workspace'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'workspace.mounts_path',
    fromKinds: ['workspace'],
    presentation: 'detail',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'workspace.uses_storage',
    fromKinds: ['workspace'],
    toKinds: ['storage.bundle', 'storage.scope'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'workspace.uses_record_store',
    fromKinds: ['workspace'],
    toKinds: ['storage.recordStore'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'workspace.uses_search_store',
    fromKinds: ['workspace'],
    toKinds: ['storage.searchStore'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'workspace.uses_asset_store',
    fromKinds: ['workspace'],
    toKinds: ['storage.assetStore'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'storage.bundle.uses_record_store',
    fromKinds: ['storage.bundle'],
    toKinds: ['storage.recordStore'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'storage.bundle.uses_search_store',
    fromKinds: ['storage.bundle'],
    toKinds: ['storage.searchStore'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'storage.bundle.uses_asset_store',
    fromKinds: ['storage.bundle'],
    toKinds: ['storage.assetStore'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'storage.scope.wraps_storage',
    fromKinds: ['storage.scope'],
    toKinds: ['storage.bundle', 'storage.scope'],
    presentation: 'both',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'constraint.applies_to',
    fromKinds: ['constraint'],
    toKinds: [
      'agent',
      'flow',
      'flow.step',
      'prompt',
      'tool',
      'media.operation',
      'composition.parallel',
      'composition.pipeline',
      'composition.swarm',
      'composition.consensus',
    ],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'guardrail.applies_to',
    fromKinds: ['guardrail'],
    toKinds: [
      'agent',
      'flow',
      'flow.step',
      'prompt',
      'tool',
      'media.operation',
      'composition.parallel',
      'composition.pipeline',
      'composition.swarm',
      'composition.consensus',
    ],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'eval.covers_definition',
    fromKinds: ['eval'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'evidence.record.declared_in',
    fromKinds: ['evidence.record'],
    presentation: 'detail',
    partial: true,
    runtimeJoin: false,
  },
] as const satisfies readonly IndexRelationPolicy[]
