import type { IndexRelationPolicy } from "./types";

export const promptContextAccessRelationPolicies = (
  ["prompt", "context"] as const
).flatMap(
  (owner) =>
    [
      {
        type: `${owner}.reads_memory`,
        fromKinds: [owner],
        toKinds: ["memory"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.writes_memory`,
        fromKinds: [owner],
        toKinds: ["memory"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.reads_blackboard`,
        fromKinds: [owner],
        toKinds: ["blackboard"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.writes_blackboard`,
        fromKinds: [owner],
        toKinds: ["blackboard"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.reads_workspace`,
        fromKinds: [owner],
        toKinds: ["workspace"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.writes_workspace`,
        fromKinds: [owner],
        toKinds: ["workspace"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
    ] satisfies IndexRelationPolicy[],
);

export const injectableUseRelationPolicies = (
  ["prompt", "context"] as const
).flatMap(
  (owner) =>
    [
      {
        type: `${owner}.uses_context`,
        fromKinds: [owner],
        toKinds: ["context"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.uses_injectable`,
        fromKinds: [owner],
        toKinds: ["injectable"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.uses_memory`,
        fromKinds: [owner],
        toKinds: ["memory"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.uses_blackboard`,
        fromKinds: [owner],
        toKinds: ["blackboard"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.uses_tool`,
        fromKinds: [owner],
        toKinds: ["tool"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
    ] satisfies IndexRelationPolicy[],
);

/** Compiler-owned authored MCP relation vocabulary. */
export const mcpRelationPolicies = [
  {
    type: "prompt.uses_mcp_server",
    fromKinds: ["prompt"],
    toKinds: ["mcp.server"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "context.uses_mcp_server",
    fromKinds: ["context"],
    toKinds: ["mcp.server"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "mcp.server.provides_tool",
    fromKinds: ["mcp.server"],
    toKinds: ["tool"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
] satisfies IndexRelationPolicy[];

export const injectableContributionRelationPolicies = [
  {
    type: "injectable.uses_context",
    fromKinds: ["injectable"],
    toKinds: ["context"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "injectable.uses_tool",
    fromKinds: ["injectable"],
    toKinds: ["tool"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
] satisfies IndexRelationPolicy[];

export const invocationAccessRelationPolicies = (
  ["prompt", "context", "tool", "agent", "flow.step"] as const
).flatMap(
  (owner) =>
    [
      {
        type: `${owner}.queries_retriever`,
        fromKinds: [owner],
        toKinds: ["rag.retriever"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.uses_scorer`,
        fromKinds: [owner],
        toKinds: ["scorer"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
      {
        type: `${owner}.runs_eval`,
        fromKinds: [owner],
        toKinds: ["evaluation"],
        presentation: "both",
        partial: true,
        runtimeJoin: true,
      },
    ] satisfies IndexRelationPolicy[],
);

export const routingTargetRelationPolicies = [
  {
    type: "router.includes_route",
    fromKinds: ["routing.router"],
    toKinds: ["routing.router.route"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "router.route.uses_router",
    fromKinds: ["routing.router.route"],
    toKinds: ["routing.router"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "router.route.uses_cascade",
    fromKinds: ["routing.router.route"],
    toKinds: ["routing.cascade"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "router.route.uses_split",
    fromKinds: ["routing.router.route"],
    toKinds: ["routing.split"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "router.route.uses_retry",
    fromKinds: ["routing.router.route"],
    toKinds: ["routing.retry"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "router.route.uses_fallback",
    fromKinds: ["routing.router.route"],
    toKinds: ["routing.fallback"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "router.route.uses_agent",
    fromKinds: ["routing.router.route"],
    toKinds: ["agent"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "router.route.uses_prompt",
    fromKinds: ["routing.router.route"],
    toKinds: ["prompt"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "cascade.includes_tier",
    fromKinds: ["routing.cascade"],
    toKinds: ["routing.cascade.tier"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "split.includes_route",
    fromKinds: ["routing.split"],
    toKinds: ["routing.split.route"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "split.route.uses_router",
    fromKinds: ["routing.split.route"],
    toKinds: ["routing.router"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "split.route.uses_split",
    fromKinds: ["routing.split.route"],
    toKinds: ["routing.split"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "split.route.uses_retry",
    fromKinds: ["routing.split.route"],
    toKinds: ["routing.retry"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "split.route.uses_cascade",
    fromKinds: ["routing.split.route"],
    toKinds: ["routing.cascade"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "split.route.uses_fallback",
    fromKinds: ["routing.split.route"],
    toKinds: ["routing.fallback"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "split.route.uses_agent",
    fromKinds: ["routing.split.route"],
    toKinds: ["agent"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "split.route.uses_prompt",
    fromKinds: ["routing.split.route"],
    toKinds: ["prompt"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "retry.uses_target",
    fromKinds: ["routing.retry"],
    toKinds: ["routing.retry.target"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "retry.target.uses_router",
    fromKinds: ["routing.retry.target"],
    toKinds: ["routing.router"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "retry.target.uses_split",
    fromKinds: ["routing.retry.target"],
    toKinds: ["routing.split"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "retry.target.uses_retry",
    fromKinds: ["routing.retry.target"],
    toKinds: ["routing.retry"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "retry.target.uses_cascade",
    fromKinds: ["routing.retry.target"],
    toKinds: ["routing.cascade"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "retry.target.uses_fallback",
    fromKinds: ["routing.retry.target"],
    toKinds: ["routing.fallback"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "retry.target.uses_agent",
    fromKinds: ["routing.retry.target"],
    toKinds: ["agent"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "retry.target.uses_prompt",
    fromKinds: ["routing.retry.target"],
    toKinds: ["prompt"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "cascade.tier.uses_router",
    fromKinds: ["routing.cascade.tier"],
    toKinds: ["routing.router"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "cascade.tier.uses_cascade",
    fromKinds: ["routing.cascade.tier"],
    toKinds: ["routing.cascade"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "cascade.tier.uses_split",
    fromKinds: ["routing.cascade.tier"],
    toKinds: ["routing.split"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "cascade.tier.uses_retry",
    fromKinds: ["routing.cascade.tier"],
    toKinds: ["routing.retry"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "cascade.tier.uses_fallback",
    fromKinds: ["routing.cascade.tier"],
    toKinds: ["routing.fallback"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "cascade.tier.uses_agent",
    fromKinds: ["routing.cascade.tier"],
    toKinds: ["agent"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "cascade.tier.uses_prompt",
    fromKinds: ["routing.cascade.tier"],
    toKinds: ["prompt"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "fallback.includes_option",
    fromKinds: ["routing.fallback"],
    toKinds: ["routing.fallback.option"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "fallback.option.uses_router",
    fromKinds: ["routing.fallback.option"],
    toKinds: ["routing.router"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "fallback.option.uses_cascade",
    fromKinds: ["routing.fallback.option"],
    toKinds: ["routing.cascade"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "fallback.option.uses_split",
    fromKinds: ["routing.fallback.option"],
    toKinds: ["routing.split"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "fallback.option.uses_retry",
    fromKinds: ["routing.fallback.option"],
    toKinds: ["routing.retry"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "fallback.option.uses_fallback",
    fromKinds: ["routing.fallback.option"],
    toKinds: ["routing.fallback"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "fallback.option.uses_agent",
    fromKinds: ["routing.fallback.option"],
    toKinds: ["agent"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "fallback.option.uses_prompt",
    fromKinds: ["routing.fallback.option"],
    toKinds: ["prompt"],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "agent.uses_routing",
    fromKinds: ["agent"],
    toKinds: [
      "routing.router",
      "routing.split",
      "routing.retry",
      "routing.cascade",
      "routing.fallback",
    ],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "flow.step.uses_routing",
    fromKinds: ["flow.step"],
    toKinds: [
      "routing.router",
      "routing.split",
      "routing.retry",
      "routing.cascade",
      "routing.fallback",
    ],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "composition.uses_routing",
    fromKinds: [
      "composition.parallel",
      "composition.pipeline",
      "composition.swarm",
      "composition.consensus",
    ],
    toKinds: [
      "routing.router",
      "routing.split",
      "routing.retry",
      "routing.cascade",
      "routing.fallback",
    ],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "parallel.branch.uses_routing",
    fromKinds: ["composition.parallel.branch"],
    toKinds: [
      "routing.router",
      "routing.split",
      "routing.retry",
      "routing.cascade",
      "routing.fallback",
    ],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
  {
    type: "pipeline.stage.uses_routing",
    fromKinds: ["composition.pipeline.stage"],
    toKinds: [
      "routing.router",
      "routing.split",
      "routing.retry",
      "routing.cascade",
      "routing.fallback",
    ],
    presentation: "both",
    partial: true,
    runtimeJoin: true,
  },
] satisfies IndexRelationPolicy[];

/** Compiler-owned authored-media relation vocabulary. */
export const mediaRelationPolicies = [
  {
    type: "media.owner",
    fromKinds: ["media.operation"],
    toKinds: [],
    presentation: "both",
    partial: true,
    runtimeJoin: false,
  },
  {
    type: "media.uses_prompt",
    fromKinds: ["media.operation"],
    toKinds: ["prompt"],
    presentation: "both",
    partial: true,
    runtimeJoin: false,
  },
  {
    type: "media.uses_routing",
    fromKinds: ["media.operation"],
    toKinds: [
      "routing.router",
      "routing.split",
      "routing.retry",
      "routing.cascade",
      "routing.fallback",
    ],
    presentation: "both",
    partial: true,
    runtimeJoin: false,
  },
  {
    type: "media.derives_with",
    fromKinds: ["ingest.source"],
    toKinds: ["media.operation"],
    presentation: "both",
    partial: true,
    runtimeJoin: false,
  },
  {
    type: "media.targets_index",
    fromKinds: ["ingest.source"],
    toKinds: ["rag.knowledgeBase", "rag.pipeline"],
    presentation: "both",
    partial: true,
    runtimeJoin: false,
  },
  {
    type: "media.targets_corpus",
    fromKinds: ["ingest.source"],
    toKinds: ["rag.knowledgeBase"],
    presentation: "both",
    partial: true,
    runtimeJoin: false,
  },
  {
    type: "media.evaluation_target",
    fromKinds: ["media.operation"],
    toKinds: [
      "evaluation",
      "eval.prompt",
      "eval.flow",
      "eval.rag",
      "eval.quality",
    ],
    presentation: "both",
    partial: true,
    runtimeJoin: false,
  },
  {
    type: "media.uses_storage",
    fromKinds: ["media.operation"],
    toKinds: ["storage.assetStore"],
    presentation: "both",
    partial: true,
    runtimeJoin: false,
  },
] satisfies IndexRelationPolicy[];
