/**
 * Durable runtime state port contract.
 *
 * The state port stores work records, idempotency keys, flow snapshots, and
 * runtime counters. Adapters persist records; the kernel owns state-machine
 * legality, retry policy, and composite transaction ordering.
 *
 * @module
 */

import type { JsonValue } from '../../storage'
import type { WorkItem } from '../engine/work'
import type { FlowId, RuntimeTargetId, WaiterId, TimerId, WorkId } from './ids'

/** Flow snapshot shape persisted by runtime-backed flow replay. */
export interface FlowSnapshot {
  /** Durable flow instance id. */
  readonly flowId: FlowId
  /** Name-based target id for the flow definition. */
  readonly targetId: RuntimeTargetId
  /** Runtime namespace. */
  readonly namespace: string
  /** Flow lifecycle status. */
  readonly status:
    | 'running'
    | 'suspended'
    | 'completed'
    | 'blocked'
    | 'cancelled'
  /** JSON input captured at first run. */
  readonly input: JsonValue
  /** Existing label-keyed step cache, unchanged by the runtime engine. */
  readonly completedSteps: Readonly<Record<string, JsonValue>>
  /** Ordered replay-structure labels observed so far. */
  readonly fingerprint: readonly string[]
  /** Suspensions currently owned by this snapshot. */
  readonly pendingSuspends: readonly RuntimePendingSuspend[]
  /** Last update time. */
  readonly updatedAt: Date
}

/** Suspension metadata stored with a flow snapshot. */
export interface RuntimePendingSuspend {
  /** User-authored suspend/wait label. */
  readonly label: string
  /** Waiter registered for event/signal delivery. */
  readonly waiterId?: WaiterId
  /** Timer registered for timeout delivery. */
  readonly timerId?: TimerId
}

/** Idempotency marker written atomically with completed transitions. */
export interface IdempotencyRecord {
  /** Runtime namespace. */
  readonly namespace: string
  /** Stable idempotency key. */
  readonly key: string
  /** Time when the guarded operation completed durably. */
  readonly completedAt: Date
}

/** Durable state read options. */
export interface RuntimeStateReadOptions {
  /** Runtime namespace. */
  readonly namespace: string
}

/** Durable state port used by the runtime kernel. */
export interface RuntimeStatePort {
  /**
   * Load a work item by id.
   *
   * Reads may happen concurrently with wake delivery. The kernel treats
   * terminal work as idempotent duplicate delivery.
   */
  getWork(
    workId: WorkId,
    options: RuntimeStateReadOptions,
  ): Promise<WorkItem | null>

  /**
   * Persist a work item produced by the kernel state machine.
   *
   * Adapters must not perform their own status transitions or retry decisions.
   */
  putWork(work: WorkItem): Promise<void>

  /**
   * Load a flow snapshot by id.
   *
   * Snapshot ids are generated by flow handles; runtime-backed replay reads
   * them through this port instead of the object-bound record-store path.
   */
  getSnapshot(
    flowId: FlowId,
    options: RuntimeStateReadOptions,
  ): Promise<FlowSnapshot | null>

  /**
   * Persist a runtime-backed flow snapshot.
   *
   * Snapshot writes participate in composite transactions in store adapters
   * that support atomic multi-record updates.
   */
  putSnapshot(snapshot: FlowSnapshot): Promise<void>

  /**
   * Check whether a stable idempotency key has already completed.
   *
   * Idempotency records are generated by the kernel and scoped by namespace.
   */
  hasIdempotencyKey(namespace: string, key: string): Promise<boolean>

  /**
   * Persist a completed idempotency record.
   *
   * Composite operations write this atomically with their state transition so a
   * crash can never record one without the other.
   */
  putIdempotencyKey(record: IdempotencyRecord): Promise<void>
}
