/**
 * Durable task delivery port contract.
 *
 * Task ports deliver small {@link RuntimeWork} routing records at least once.
 * The kernel, not the adapter, owns idempotency, retry state, and terminal
 * work transitions. Queue work is acknowledged only after durable state
 * transition succeeds.
 *
 * @module
 */

import type { LeaseToken, TaskId } from './ids'
import type { RuntimeWork } from './work'

/** Options for enqueuing runtime work. */
export interface EnqueueOptions {
  /** Stable key for duplicate enqueue protection. */
  readonly idempotencyKey?: string
  /** Earliest delivery time for delayed retries or timers. */
  readonly notBefore?: Date
}

/** Adapter-owned delivery record. */
export interface EnqueuedTask {
  /** Adapter-generated delivery id. */
  readonly taskId: TaskId
  /** Small routing work payload. */
  readonly work: RuntimeWork
  /** Time when delivery became durable. */
  readonly enqueuedAt: Date
}

/** Error reported to a task adapter when delivery processing fails. */
export interface RuntimeTaskError {
  /** Stable runtime or adapter diagnostic code. */
  readonly code: string
  /** Human-readable failure summary. */
  readonly message: string
  /** Whether the adapter should consider this failure retryable. */
  readonly retryable: boolean
  /** Original thrown value, preserved only for diagnostics. */
  readonly cause?: unknown
}

/** Durable at-least-once work delivery port. */
export interface DurableTaskPort {
  /**
   * Enqueue small runtime work for at-least-once delivery.
   *
   * Concurrent duplicate enqueue calls with the same idempotency key must not
   * create multiple logical deliveries.
   */
  enqueue(work: RuntimeWork, options?: EnqueueOptions): Promise<EnqueuedTask>

  /**
   * Acknowledge delivery after the kernel commits a durable state transition.
   *
   * Lease tokens are generated by the lease port or queue adapter and prove the
   * caller owns the delivery being acknowledged.
   */
  ack(taskId: TaskId, lease: LeaseToken): Promise<void>

  /**
   * Report adapter-level delivery failure.
   *
   * The kernel owns logical retry/dead-letter state; this method is for queue
   * bookkeeping when a transport requires explicit failure notification.
   */
  fail(
    taskId: TaskId,
    lease: LeaseToken,
    error: RuntimeTaskError,
  ): Promise<void>
}
