/**
 * Hook and middleware type definitions for prompt execution.
 *
 * This module owns the per-call hook *function* types (resolve, execution,
 * stream-progress, stream-start).
 *
 * Types are defined here; hook state lives in `./runtime`.
 * Consumers read hooks via `getHooks()` from `./runtime`.
 *
 * @module
 */

import type { InspectResult } from '../resolver/types'

// ─────────────────────────────────────────────────────────────────
// Resolve Hook (for agent adapters)
// ─────────────────────────────────────────────────────────────────

/** Arguments passed to the resolve hook. */
export interface ResolveHookArgs {
  promptId: string | undefined
  input: Record<string, unknown>
  inspect: InspectResult
  /** Source location of the resolve() call site. */
  source?: { file: string; line: number; column?: number; function?: string }
}

/** Result returned by a resolve hook to propagate context. */
export interface ResolveHookResult {
  /** The traceId assigned to this resolve event, for parent-child linking. */
  traceId?: string
}

/** A function that receives resolve events (e.g. for devtools tracing). */
export type ResolveHook = (
  args: ResolveHookArgs,
) => void | ResolveHookResult | Promise<void | ResolveHookResult | undefined>

// ─────────────────────────────────────────────────────────────────
// Execution Hook (for model call tracing)
// ─────────────────────────────────────────────────────────────────

/** Arguments passed to the execution hook after each model call. */
export interface ExecutionHookArgs {
  promptId: string | undefined
  startedAt: number
  durationMs: number
  model: string
  provider: string
  usage?: { inputTokens?: number; outputTokens?: number }
  cost?: number
  modelId?: string
  toolCalls?: Array<{ id?: string; name: string; args: unknown }>
  finishReason?: string
  error?: string
  /** Trace ID generated by the middleware, so the hook uses it instead of generating its own. */
  traceId?: string
  /** Parent trace ID from the resolve() call, for nesting agent-step under resolve. */
  parentResolveTraceId?: string
  /** Inspect data from the resolve() call, so agent-step traces inherit tools/system parts. */
  resolveInspect?: InspectResult
  /** Streaming metrics (TTFT, tokens/sec, chunk count). */
  streaming?: { ttftMs?: number; tokensPerSecond?: number; totalChunks?: number }
  /** When true, stream-start observability was already sent eagerly. The handler should skip sending it again. */
  streamStartSent?: boolean
}

/** A function that receives model execution events. */
export type ExecutionHook = (args: ExecutionHookArgs) => void | Promise<void>

// ─────────────────────────────────────────────────────────────────
// Stream Progress Hook (for live streaming metrics)
// ─────────────────────────────────────────────────────────────────

/** A progress reporter returned by the stream progress hook. */
export interface StreamProgressReporter {
  onChunk: (textDelta?: string) => void
  flush: () => Promise<void>
  dispose: () => void
}

/** Creates a progress reporter for a given trace. Returns undefined to skip. */
export type StreamProgressHook = (traceId: string) => StreamProgressReporter | undefined

/** Args for the eager stream start hook (fires before streaming begins). */
export interface StreamStartHookArgs {
  traceId: string
  promptId: string | undefined
  startedAt: number
  model: string
  provider: string
  parentResolveTraceId?: string
}

/** Fires immediately when a stream begins, before any chunks arrive. */
export type StreamStartHook = (args: StreamStartHookArgs) => void | Promise<void>
