import type { ProjectDefinitionKind, ProjectRelation, SourceLocation } from '@crux/core/catalog'

export type CatalogRelationPresentation = 'edge' | 'detail' | 'both'

export interface CatalogRelationPolicy {
  readonly type: string
  readonly fromKinds?: readonly ProjectDefinitionKind[]
  readonly toKinds?: readonly ProjectDefinitionKind[]
  readonly presentation: CatalogRelationPresentation
  readonly partial: boolean
  readonly runtimeJoin: boolean
}

const promptContextAccessRelationPolicies = (['prompt', 'context'] as const).flatMap((owner) => [
  {
    type: `${owner}.reads_memory`,
    fromKinds: [owner],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.writes_memory`,
    fromKinds: [owner],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.reads_blackboard`,
    fromKinds: [owner],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.writes_blackboard`,
    fromKinds: [owner],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.reads_workspace`,
    fromKinds: [owner],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.writes_workspace`,
    fromKinds: [owner],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
] satisfies CatalogRelationPolicy[])

const injectableUseRelationPolicies = (['prompt', 'context'] as const).flatMap((owner) => [
  {
    type: `${owner}.uses_context`,
    fromKinds: [owner],
    toKinds: ['context'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.uses_injectable`,
    fromKinds: [owner],
    toKinds: ['injectable'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.uses_memory`,
    fromKinds: [owner],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.uses_blackboard`,
    fromKinds: [owner],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.uses_tool`,
    fromKinds: [owner],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
] satisfies CatalogRelationPolicy[])

const injectableContributionRelationPolicies = [
  {
    type: 'injectable.uses_context',
    fromKinds: ['injectable'],
    toKinds: ['context'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'injectable.uses_tool',
    fromKinds: ['injectable'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
] satisfies CatalogRelationPolicy[]

const invocationAccessRelationPolicies = (['prompt', 'context', 'tool', 'agent', 'flow.step'] as const).flatMap((owner) => [
  {
    type: `${owner}.queries_retriever`,
    fromKinds: [owner],
    toKinds: ['rag.retriever'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.uses_scorer`,
    fromKinds: [owner],
    toKinds: ['scorer'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: `${owner}.runs_eval`,
    fromKinds: [owner],
    toKinds: ['eval.prompt', 'eval.flow', 'eval.rag', 'eval.quality'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
] satisfies CatalogRelationPolicy[])

const routingTargetRelationPolicies = [
  {
    type: 'router.includes_route',
    fromKinds: ['routing.router'],
    toKinds: ['routing.router.route'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'router.route.uses_router',
    fromKinds: ['routing.router.route'],
    toKinds: ['routing.router'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'router.route.uses_cascade',
    fromKinds: ['routing.router.route'],
    toKinds: ['routing.cascade'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'router.route.uses_fallback',
    fromKinds: ['routing.router.route'],
    toKinds: ['routing.fallback'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'router.route.uses_agent',
    fromKinds: ['routing.router.route'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'router.route.uses_prompt',
    fromKinds: ['routing.router.route'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'cascade.includes_tier',
    fromKinds: ['routing.cascade'],
    toKinds: ['routing.cascade.tier'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'cascade.tier.uses_router',
    fromKinds: ['routing.cascade.tier'],
    toKinds: ['routing.router'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'cascade.tier.uses_cascade',
    fromKinds: ['routing.cascade.tier'],
    toKinds: ['routing.cascade'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'cascade.tier.uses_fallback',
    fromKinds: ['routing.cascade.tier'],
    toKinds: ['routing.fallback'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'cascade.tier.uses_agent',
    fromKinds: ['routing.cascade.tier'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'cascade.tier.uses_prompt',
    fromKinds: ['routing.cascade.tier'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'fallback.includes_option',
    fromKinds: ['routing.fallback'],
    toKinds: ['routing.fallback.option'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'fallback.option.uses_router',
    fromKinds: ['routing.fallback.option'],
    toKinds: ['routing.router'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'fallback.option.uses_cascade',
    fromKinds: ['routing.fallback.option'],
    toKinds: ['routing.cascade'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'fallback.option.uses_fallback',
    fromKinds: ['routing.fallback.option'],
    toKinds: ['routing.fallback'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'fallback.option.uses_agent',
    fromKinds: ['routing.fallback.option'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'fallback.option.uses_prompt',
    fromKinds: ['routing.fallback.option'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.uses_routing',
    fromKinds: ['agent'],
    toKinds: ['routing.router', 'routing.cascade', 'routing.fallback'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_routing',
    fromKinds: ['flow.step'],
    toKinds: ['routing.router', 'routing.cascade', 'routing.fallback'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'composition.uses_routing',
    fromKinds: ['composition.parallel', 'composition.pipeline', 'composition.swarm', 'composition.consensus'],
    toKinds: ['routing.router', 'routing.cascade', 'routing.fallback'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.branch.uses_routing',
    fromKinds: ['composition.parallel.branch'],
    toKinds: ['routing.router', 'routing.cascade', 'routing.fallback'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.stage.uses_routing',
    fromKinds: ['composition.pipeline.stage'],
    toKinds: ['routing.router', 'routing.cascade', 'routing.fallback'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
] satisfies CatalogRelationPolicy[]

export const catalogRelationPolicies = [
  ...injectableUseRelationPolicies,
  ...injectableContributionRelationPolicies,
  ...promptContextAccessRelationPolicies,
  {
    type: 'agent.uses_prompt',
    fromKinds: ['agent'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.uses_tool',
    fromKinds: ['agent'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.can_handoff_to',
    fromKinds: ['agent'],
    toKinds: ['agent'],
    presentation: 'edge',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.reads_memory',
    fromKinds: ['agent'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.writes_memory',
    fromKinds: ['agent'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.reads_blackboard',
    fromKinds: ['agent'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.writes_blackboard',
    fromKinds: ['agent'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.reads_workspace',
    fromKinds: ['agent'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'agent.writes_workspace',
    fromKinds: ['agent'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.reads_memory',
    fromKinds: ['tool'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.writes_memory',
    fromKinds: ['tool'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.reads_blackboard',
    fromKinds: ['tool'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.writes_blackboard',
    fromKinds: ['tool'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.reads_workspace',
    fromKinds: ['tool'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'tool.writes_workspace',
    fromKinds: ['tool'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.includes_step',
    fromKinds: ['flow'],
    toKinds: ['flow.step'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_prompt',
    fromKinds: ['flow.step'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_agent',
    fromKinds: ['flow.step'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_tool',
    fromKinds: ['flow.step'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_memory',
    fromKinds: ['flow.step'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.uses_blackboard',
    fromKinds: ['flow.step'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.reads_memory',
    fromKinds: ['flow.step'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.writes_memory',
    fromKinds: ['flow.step'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.reads_blackboard',
    fromKinds: ['flow.step'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.writes_blackboard',
    fromKinds: ['flow.step'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.reads_workspace',
    fromKinds: ['flow.step'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.writes_workspace',
    fromKinds: ['flow.step'],
    toKinds: ['workspace'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'flow.step.waits_for_signal',
    fromKinds: ['flow.step'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  ...invocationAccessRelationPolicies,
  ...routingTargetRelationPolicies,
  {
    type: 'composition.uses_agent',
    fromKinds: ['composition.parallel', 'composition.pipeline', 'composition.swarm', 'composition.consensus'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'composition.uses_flow',
    fromKinds: ['composition.parallel', 'composition.pipeline', 'composition.swarm', 'composition.consensus'],
    toKinds: ['flow'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'composition.uses_prompt',
    fromKinds: ['composition.parallel', 'composition.pipeline', 'composition.swarm', 'composition.consensus'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'composition.uses_tool',
    fromKinds: ['composition.parallel', 'composition.pipeline', 'composition.swarm', 'composition.consensus'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.includes_branch',
    fromKinds: ['composition.parallel'],
    toKinds: ['composition.parallel.branch'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.branch.uses_agent',
    fromKinds: ['composition.parallel.branch'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.branch.uses_flow',
    fromKinds: ['composition.parallel.branch'],
    toKinds: ['flow'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.branch.uses_prompt',
    fromKinds: ['composition.parallel.branch'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'parallel.branch.uses_tool',
    fromKinds: ['composition.parallel.branch'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.includes_stage',
    fromKinds: ['composition.pipeline'],
    toKinds: ['composition.pipeline.stage'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.stage.uses_agent',
    fromKinds: ['composition.pipeline.stage'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.stage.uses_flow',
    fromKinds: ['composition.pipeline.stage'],
    toKinds: ['flow'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.stage.uses_prompt',
    fromKinds: ['composition.pipeline.stage'],
    toKinds: ['prompt'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'pipeline.stage.uses_tool',
    fromKinds: ['composition.pipeline.stage'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'consensus.includes_agent',
    fromKinds: ['composition.consensus'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'consensus.uses_judge',
    fromKinds: ['composition.consensus'],
    toKinds: ['agent', 'scorer'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'consensus.uses_scorer',
    fromKinds: ['composition.consensus'],
    toKinds: ['scorer'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'swarm.includes_agent',
    fromKinds: ['composition.swarm'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'swarm.coordinated_by',
    fromKinds: ['composition.swarm'],
    toKinds: ['agent'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'swarm.uses_blackboard',
    fromKinds: ['composition.swarm'],
    toKinds: ['blackboard'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'swarm.uses_memory',
    fromKinds: ['composition.swarm'],
    toKinds: ['memory'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.pipeline.uses_retriever',
    fromKinds: ['rag.pipeline'],
    toKinds: ['rag.retriever'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.pipeline.includes_stage',
    fromKinds: ['rag.pipeline'],
    toKinds: ['rag.pipeline.stage'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.pipeline.stage.uses_retriever',
    fromKinds: ['rag.pipeline.stage'],
    toKinds: ['rag.retriever'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'rag.pipeline.stage.uses_scorer',
    fromKinds: ['rag.pipeline.stage'],
    toKinds: ['scorer'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'memory.includes_block',
    fromKinds: ['memory'],
    toKinds: ['memory.block'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'memory.uses_store',
    fromKinds: ['memory'],
    toKinds: ['memory.store'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'blackboard.uses_store',
    fromKinds: ['blackboard'],
    toKinds: ['memory.store'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'blackboard.uses_schema',
    fromKinds: ['blackboard'],
    presentation: 'detail',
    partial: true,
    runtimeJoin: false,
  },
  {
    type: 'workspace.exposes_tool',
    fromKinds: ['workspace'],
    toKinds: ['tool'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'workspace.mounts_path',
    fromKinds: ['workspace'],
    presentation: 'detail',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'constraint.applies_to',
    fromKinds: ['constraint'],
    toKinds: ['agent', 'flow', 'flow.step', 'prompt', 'tool', 'composition.parallel', 'composition.pipeline', 'composition.swarm', 'composition.consensus'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'guardrail.applies_to',
    fromKinds: ['guardrail'],
    toKinds: ['agent', 'flow', 'flow.step', 'prompt', 'tool', 'composition.parallel', 'composition.pipeline', 'composition.swarm', 'composition.consensus'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
  {
    type: 'eval.covers_definition',
    fromKinds: ['eval.prompt', 'eval.flow', 'eval.rag', 'eval.quality'],
    presentation: 'both',
    partial: true,
    runtimeJoin: true,
  },
] as const satisfies readonly CatalogRelationPolicy[]

export function relationPolicyFor(type: string): CatalogRelationPolicy | undefined {
  return catalogRelationPolicies.find((policy) => policy.type === type)
}

export function staticRelationId(from: string, type: string, to: string): string {
  return resolvedRelationId(type, from, to)
}

export function resolvedRelationId(type: string, from: string, to: string): string {
  return `relation:${type}:${from}:${to}`
}

export function projectRelation(input: {
  readonly type: string
  readonly from: string
  readonly to: string
  readonly fidelity: ProjectRelation['fidelity']
  readonly source?: SourceLocation
  readonly id?: string
}): ProjectRelation {
  return {
    id: input.id ?? (input.fidelity === 'resolved' ? resolvedRelationId(input.type, input.from, input.to) : staticRelationId(input.from, input.type, input.to)),
    type: input.type,
    from: input.from,
    to: input.to,
    fidelity: input.fidelity,
    ...(input.source ? { source: input.source } : {}),
  }
}
