package protocol

const (
	MethodInitialize             = "initialize"
	MethodInitialized            = "initialized"
	MethodShutdown               = "shutdown"
	MethodExit                   = "exit"
	MethodDidOpen                = "textDocument/didOpen"
	MethodDidClose               = "textDocument/didClose"
	MethodDidSave                = "textDocument/didSave"
	MethodDidChange              = "textDocument/didChange"
	MethodHover                  = "textDocument/hover"
	MethodDefinition             = "textDocument/definition"
	MethodReferences             = "textDocument/references"
	MethodDocumentSymbol         = "textDocument/documentSymbol"
	MethodFoldingRange           = "textDocument/foldingRange"
	MethodInlayHint              = "textDocument/inlayHint"
	MethodCodeLens               = "textDocument/codeLens"
	MethodCompletion             = "textDocument/completion"
	MethodCodeAction             = "textDocument/codeAction"
	MethodDidChangeConfiguration = "workspace/didChangeConfiguration"
	MethodWorkspaceSymbol        = "workspace/symbol"
	MethodExecuteCommand         = "workspace/executeCommand"
	MethodInlayHintRefresh       = "workspace/inlayHint/refresh"
	MethodCodeLensRefresh        = "workspace/codeLens/refresh"
	MethodPromptTextDecorations  = "crux/promptText/decorations"
	MethodPromptTextRefresh      = "crux/promptText/refresh"
	MethodPublishDiagnostics     = "textDocument/publishDiagnostics"
	MethodLogMessage             = "window/logMessage"
	MethodShowMessage            = "window/showMessage"
	MethodCancelRequest          = "$/cancelRequest"
)
