import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import type { ProjectDefinition } from '@use-crux/core/project-index'
import type { RuntimeArtifactManifest, RuntimeArtifactManifestTarget } from '@use-crux/core/runtime'
import { createRuntimeError } from '@use-crux/core/runtime'
import ts from 'typescript'
import { loadProjectConfig } from './config'
import { staticDefinitionFiles } from './files'
import { createStaticExtraction } from './static/extraction/engine'

const GENERATED_HEADER = [
  '/*',
  ' * This file is generated by Crux. Do not edit.',
  ' * It will be overwritten by `crux runtime generate` and `crux dev`.',
  ' */',
].join('\n')
const LEGACY_GENERATED_HEADER = '/* This file is generated by Crux. Do not edit by hand. */'

export type RuntimeArtifactHost = 'next' | 'convex'

/** Options for generating runtime target manifests and host entry files. */
export interface GenerateRuntimeArtifactsOptions {
  /** Project root containing authored Crux source files. */
  readonly root: string
  /** Optional explicit source files. Defaults to Project Index static discovery. */
  readonly files?: readonly string[]
  /** Runtime host entry to generate. Defaults to `config({ runtime })` or Next. */
  readonly host?: RuntimeArtifactHost
}

/** Result of a runtime artifact generation pass. */
export interface RuntimeArtifactGenerationResult {
  /** Deterministic runtime target manifest written to `.crux/generated/runtime/manifest.json`. */
  readonly manifest: RuntimeArtifactManifest
  /** SHA-256 hash of the canonical manifest contents, excluding generated entry files. */
  readonly contentHash: string
  /** Absolute files written by this generation pass. */
  readonly writtenFiles: readonly string[]
}

/** Drift report for non-terminal durable work whose target is absent from the manifest. */
export interface RuntimeArtifactDriftReport {
  /** Target ids that still have non-terminal durable work but are missing from generated artifacts. */
  readonly missingTargets: readonly RuntimeArtifactMissingTarget[]
}

/** One missing target and the affected non-terminal work count. */
export interface RuntimeArtifactMissingTarget {
  /** Durable target id stored on pending/suspended work. */
  readonly targetId: string
  /** Count of non-terminal work records that still reference the target. */
  readonly count: number
}

/** Generate the runtime manifest and default Next/Convex entry files for a project. */
export async function generateRuntimeArtifacts(
  options: GenerateRuntimeArtifactsOptions,
): Promise<RuntimeArtifactGenerationResult> {
  const host = await resolveRuntimeArtifactHost(options)
  const files = options.files ?? staticDefinitionFiles(options.root)
  const extraction = createStaticExtraction({ root: options.root, cache: 'none' })
  const extracted = await extraction.extractFiles([...files].sort(compareCodepoint))
  const manifest = manifestFromDefinitions({
    root: options.root,
    definitions: extracted.flatMap((item) => item.definitions),
  })
  await validateTargetExports(options.root, manifest.targets)
  const canonicalManifest = `${JSON.stringify(manifest, null, 2)}\n`
  const contentHash = createHash('sha256').update(canonicalManifest).digest('hex')

  const manifestFile = join(options.root, '.crux/generated/runtime/manifest.json')
  const nextFile = join(options.root, 'crux.generated/next.ts')
  const convexGeneratedFile = join(options.root, 'convex/_crux/generated.ts')
  const convexTargetsFile = join(options.root, 'convex/_crux/targets.ts')
  const writtenFiles: string[] = []
  if (await writeGeneratedFile(manifestFile, canonicalManifest)) {
    writtenFiles.push(manifestFile)
  }
  if (host === 'next') {
    if (
      await writeGeneratedFile(nextFile, nextEntryFile(manifest, nextFile, options.root, contentHash), {
        protect: true,
      })
    ) {
      writtenFiles.push(nextFile)
    }
  }
  if (host === 'convex') {
    if (await writeGeneratedFile(convexGeneratedFile, convexGeneratedEntryFile(), { protect: true })) {
      writtenFiles.push(convexGeneratedFile)
    }
    if (
      await writeGeneratedFile(convexTargetsFile, convexTargetEntryFile(manifest, convexTargetsFile, options.root), {
        protect: true,
      })
    ) {
      writtenFiles.push(convexTargetsFile)
    }
  }

  return {
    manifest,
    contentHash,
    writtenFiles,
  }
}

/** Project runtime definitions into the v1 runtime artifact manifest. */
export function manifestFromDefinitions(input: {
  readonly root: string
  readonly definitions: readonly ProjectDefinition[]
}): RuntimeArtifactManifest {
  const targets = input.definitions.flatMap((definition) => targetFromDefinition(input.root, definition))
  const seen = new Set<string>()
  for (const target of targets) {
    if (seen.has(target.name)) throw duplicateTargetError(target.name)
    seen.add(target.name)
  }
  return {
    version: 1,
    targets: [...targets].sort((a, b) => compareCodepoint(a.name, b.name) || compareCodepoint(a.kind, b.kind)),
  }
}

/** Compare manifest target names with target ids found in non-terminal runtime store rows. */
export function diffRuntimeArtifactDrift(input: {
  readonly manifest: RuntimeArtifactManifest
  readonly nonTerminalTargetIds: readonly string[]
}): RuntimeArtifactDriftReport {
  const manifestNames = new Set(input.manifest.targets.map((target) => target.name))
  const counts = new Map<string, number>()
  for (const targetId of input.nonTerminalTargetIds) {
    if (manifestNames.has(targetId)) continue
    counts.set(targetId, (counts.get(targetId) ?? 0) + 1)
  }
  return {
    missingTargets: [...counts]
      .map(([targetId, count]) => ({ targetId, count }))
      .sort((a, b) => compareCodepoint(a.targetId, b.targetId)),
  }
}

function targetFromDefinition(root: string, definition: ProjectDefinition): readonly RuntimeArtifactManifestTarget[] {
  if (definition.kind !== 'flow' && definition.kind !== 'task') return []
  const exportName = typeof definition.metadata?.exportName === 'string' ? definition.metadata.exportName : undefined
  const file = definition.source?.file
  if (!exportName || !file) return []
  return [
    {
      name: definition.name,
      kind: definition.kind,
      module: `./${relative(root, file).replace(/\\/g, '/')}`,
      export: exportName,
    },
  ]
}

function nextEntryFile(
  manifest: RuntimeArtifactManifest,
  outputFile: string,
  root: string,
  manifestHash: string,
): string {
  return [
    GENERATED_HEADER,
    "import { createRuntimeHandler } from '@use-crux/core/runtime'",
    ...targetImports(manifest, outputFile, root),
    '',
    `const targets = [${targetLocalNames(manifest).join(', ')}] as const`,
    '',
    `export const { GET, POST } = createRuntimeHandler({ targets, manifestHash: '${manifestHash}' })`,
    '',
  ].join('\n')
}

function convexGeneratedEntryFile(): string {
  return [
    GENERATED_HEADER,
    "import { makeFunctionReference } from 'convex/server'",
    "import { createConvexRuntimeHandlers } from '@use-crux/convex/runtime'",
    "import { components } from '../_generated/api'",
    '',
    "const targetExecutor = makeFunctionReference<'action', { envelope: unknown }, unknown>(",
    "  '_crux/targets:executeTarget',",
    ')',
    '',
    'const runtime = createConvexRuntimeHandlers({ component: components.crux, targetExecutor })',
    '',
    'export const { deliverSignal, fireTimer, handleWake, resumeFlow, runTask } = runtime',
    '',
  ].join('\n')
}

function convexTargetEntryFile(manifest: RuntimeArtifactManifest, outputFile: string, root: string): string {
  return [
    GENERATED_HEADER,
    "'use node'",
    '',
    "import { createConvexRuntimeTargetExecutor } from '@use-crux/convex/runtime/node'",
    "import { components } from '../_generated/api'",
    ...targetImports(manifest, outputFile, root),
    '',
    `const targets = [${targetLocalNames(manifest).join(', ')}] as const`,
    '',
    'const runtime = createConvexRuntimeTargetExecutor({ component: components.crux, targets })',
    '',
    'export const { executeTarget } = runtime',
    '',
  ].join('\n')
}

function targetImports(manifest: RuntimeArtifactManifest, outputFile: string, root: string): string[] {
  return manifest.targets.map((target, index) => {
    const sourceFile = join(root, target.module.replace(/^\.\//, ''))
    const specifier = importSpecifier(dirname(outputFile), sourceFile)
    return `import { ${target.export} as ${targetLocalName(index)} } from '${specifier}'`
  })
}

function targetLocalNames(manifest: RuntimeArtifactManifest): string[] {
  return manifest.targets.map((_, index) => targetLocalName(index))
}

function targetLocalName(index: number): string {
  return `target${index}`
}

function importSpecifier(fromDir: string, toFile: string): string {
  const withoutExtension = toFile.replace(/\.(tsx?|jsx?|mjs|cjs)$/, '')
  let specifier = relative(fromDir, withoutExtension).replace(/\\/g, '/')
  if (!specifier.startsWith('.')) specifier = `./${specifier}`
  return specifier
}

async function resolveRuntimeArtifactHost(options: GenerateRuntimeArtifactsOptions): Promise<RuntimeArtifactHost> {
  if (options.host) return options.host
  const loaded = await loadProjectConfig(options.root, undefined, 'runtime-rich')
  const runtime = loaded.loaded.crux?.config.runtime
  if (runtime?.kind === 'host-bound' && runtime.host === 'convex') return 'convex'
  if (loaded.loaded.configFile && !loaded.loaded.crux) {
    throw createRuntimeError({
      code: 'SETUP_REQUIRED',
      whatFailed: 'Crux runtime artifacts could not resolve the configured runtime host.',
      why: `The config file \`${loaded.loaded.configFile}\` did not load to a Crux config object, so the generator cannot choose a host entry safely.`,
      whatStillWorks: 'The runtime manifest and entry files are unchanged.',
      nextStep: 'Fix crux.config.ts or pass an explicit host to crux runtime generate.',
    })
  }
  return 'next'
}

async function validateTargetExports(root: string, targets: readonly RuntimeArtifactManifestTarget[]): Promise<void> {
  const byFile = new Map<string, Set<string>>()
  for (const target of targets) {
    const file = join(root, target.module.replace(/^\.\//, ''))
    const exports = byFile.get(file) ?? new Set<string>()
    exports.add(target.export)
    byFile.set(file, exports)
  }
  await Promise.all(
    [...byFile].map(async ([file, exports]) => {
      const source = await readFile(file, 'utf8')
      const namedExports = namedValueExports(file, source)
      for (const exportName of exports) {
        if (!namedExports.has(exportName)) throw targetNotExportedError(file, exportName)
      }
    }),
  )
}

function namedValueExports(file: string, source: string): Set<string> {
  const sourceFile = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true)
  const exports = new Set<string>()
  for (const statement of sourceFile.statements) {
    if (hasExportModifier(statement)) {
      if (ts.isVariableStatement(statement)) {
        for (const declaration of statement.declarationList.declarations) {
          if (ts.isIdentifier(declaration.name)) exports.add(declaration.name.text)
        }
      } else if ((ts.isFunctionDeclaration(statement) || ts.isClassDeclaration(statement)) && statement.name) {
        exports.add(statement.name.text)
      }
    }
    if (ts.isExportDeclaration(statement) && statement.exportClause && ts.isNamedExports(statement.exportClause)) {
      for (const element of statement.exportClause.elements) {
        exports.add(element.name.text)
      }
    }
  }
  return exports
}

function hasExportModifier(statement: ts.Statement): boolean {
  return (
    ts.canHaveModifiers(statement) &&
    (ts.getModifiers(statement) ?? []).some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword)
  )
}

async function writeGeneratedFile(
  file: string,
  contents: string,
  options: { readonly protect?: boolean } = {},
): Promise<boolean> {
  const existing = await readExistingFile(file)
  if (options.protect) assertGeneratedFileContentsWritable(file, existing)
  if (existing === contents) return false
  await mkdir(dirname(file), { recursive: true })
  await writeFile(file, contents)
  return true
}

async function generatedFileMatches(file: string, contents: string): Promise<boolean> {
  return (await readExistingFile(file)) === contents
}

async function readExistingFile(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, 'utf8')
  } catch (error) {
    if (isNodeError(error) && error.code === 'ENOENT') return undefined
    throw error
  }
}

async function assertGeneratedFileWritable(file: string): Promise<void> {
  assertGeneratedFileContentsWritable(file, await readExistingFile(file))
}

function assertGeneratedFileContentsWritable(file: string, existing: string | undefined): void {
  if (existing === undefined || isGeneratedRuntimeArtifact(existing)) return
  throw createRuntimeError({
    code: 'ARTIFACTS_STALE',
    whatFailed: `Crux runtime artifact \`${file}\` is not marked as generated.`,
    why: 'The generator will not overwrite user-authored files without the Crux generated-file marker.',
    whatStillWorks:
      'The existing file is unchanged, and other generated artifacts can be regenerated after the path is cleared.',
    nextStep: 'Move or rename the user-authored file, then run `crux runtime generate` again.',
  })
}

function isGeneratedRuntimeArtifact(contents: string): boolean {
  return contents.startsWith(GENERATED_HEADER) || contents.startsWith(LEGACY_GENERATED_HEADER)
}

function duplicateTargetError(name: string): never {
  throw createRuntimeError({
    code: 'TARGET_DUPLICATE',
    whatFailed: `Runtime target \`${name}\` is discovered more than once.`,
    why: 'Generated runtime artifacts need one stable target for each durable name.',
    whatStillWorks: 'Other uniquely named runtime targets can still be discovered.',
    nextStep: 'Rename one target or remove the duplicate export, then run `crux runtime generate` again.',
  })
}

function targetNotExportedError(file: string, exportName: string): never {
  throw createRuntimeError({
    code: 'TARGET_NOT_EXPORTED',
    whatFailed: `Runtime target export \`${exportName}\` was not found in \`${file}\`.`,
    why: 'Generated runtime entries import targets by named export, and default or local-only targets cannot be wired durably.',
    whatStillWorks: 'Other runtime targets with named exports can still be generated.',
    nextStep: `Export the target as \`export const ${exportName} = ...\`, then run \`crux runtime generate\` again.`,
  })
}

function compareCodepoint(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error
}
