import { randomUUID } from "node:crypto";
import {
  lstat,
  mkdir,
  readFile,
  realpath,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import { dirname, isAbsolute, posix, relative, resolve, sep } from "node:path";
import { createRuntimeError } from "@use-crux/core/runtime";
import {
  RuntimeArtifactGenerationError,
  runtimeArtifactFindingFromError,
} from "./findings";

export const GENERATED_HEADER = [
  "/*",
  " * This file is generated by Crux. Do not edit.",
  " * It will be overwritten by `crux runtime generate` and `crux dev`.",
  " */",
].join("\n");

const LEGACY_GENERATED_HEADER =
  "/* This file is generated by Crux. Do not edit by hand. */";

export interface RuntimeArtifactPlanFile {
  /** Canonical project-root-relative POSIX destination. */
  readonly destination: string;
  readonly contents: string;
  readonly ownership: "crux-owned" | "generated-marker";
  readonly activationOrder: number;
  readonly conflictNextStep?: string;
}

export interface RuntimeArtifactPlan {
  readonly root: string;
  readonly files: readonly RuntimeArtifactPlanFile[];
}

interface PreparedRuntimeArtifactFile extends RuntimeArtifactPlanFile {
  readonly file: string;
  readonly existing: string | undefined;
  readonly changed: boolean;
}

export interface PreparedRuntimeArtifactPlan {
  readonly root: string;
  readonly files: readonly PreparedRuntimeArtifactFile[];
}

/** Construct and validate the complete in-memory artifact plan. */
export function createRuntimeArtifactPlan(input: {
  readonly root: string;
  readonly files: readonly RuntimeArtifactPlanFile[];
}): RuntimeArtifactPlan {
  const root = resolve(input.root);
  const seen = new Set<string>();
  const files = input.files.map((file) => {
    assertCanonicalDestination(file.destination);
    if (seen.has(file.destination)) {
      throw new TypeError(
        `Runtime artifact plan contains duplicate destination '${file.destination}'.`,
      );
    }
    seen.add(file.destination);
    return Object.freeze({ ...file });
  });
  return Object.freeze({ root, files: Object.freeze(files) });
}

/** Read and validate every destination before the first artifact write. */
export async function preflightRuntimeArtifactPlan(
  plan: RuntimeArtifactPlan,
): Promise<PreparedRuntimeArtifactPlan> {
  const rootRealPath = await realpath(plan.root);
  const files: PreparedRuntimeArtifactFile[] = [];
  const findings = [];
  for (const planned of plan.files) {
    try {
      const file = resolve(plan.root, planned.destination);
      assertWithinRoot(plan.root, file, planned.destination);
      await assertRealPathSafe(rootRealPath, file, planned.destination);
      const existing = await readExistingFile(file);
      if (planned.ownership === "generated-marker") {
        assertGeneratedFileContentsWritable(
          file,
          existing,
          planned.conflictNextStep,
        );
      }
      files.push(
        Object.freeze({
          ...planned,
          file,
          existing,
          changed: existing !== planned.contents,
        }),
      );
    } catch (error) {
      const protectedConflict =
        typeof error === "object" &&
        error !== null &&
        "code" in error &&
        error.code === "ARTIFACTS_STALE";
      findings.push(
        runtimeArtifactFindingFromError(error, {
          featureKind: "generated-file",
          featureId: planned.destination,
          source: planned.destination,
          ...(protectedConflict
            ? {
                summary: `Crux cannot update '${planned.destination}' because it is not a generated file.`,
              }
            : {}),
        }),
      );
    }
  }
  if (findings.length > 0) {
    throw new RuntimeArtifactGenerationError(findings);
  }
  return Object.freeze({ root: plan.root, files: Object.freeze(files) });
}

/** Stage every changed file, then atomically activate the manifest last. */
export async function commitRuntimeArtifactPlan(
  plan: PreparedRuntimeArtifactPlan,
): Promise<readonly string[]> {
  const changed = plan.files
    .filter((file) => file.changed)
    .sort(
      (left, right) =>
        left.activationOrder - right.activationOrder ||
        compareCodepoint(left.destination, right.destination),
    );
  if (changed.length === 0) return Object.freeze([]);

  const staged: Array<{
    readonly entry: PreparedRuntimeArtifactFile;
    readonly temporaryFile: string;
  }> = [];
  try {
    for (const entry of changed) {
      await mkdir(dirname(entry.file), { recursive: true });
      const temporaryFile = siblingTemporaryFile(entry.file);
      staged.push({ entry, temporaryFile });
      await writeFile(temporaryFile, entry.contents, {
        encoding: "utf8",
        flag: "wx",
      });
    }
  } catch (error) {
    await cleanupTemporaryFiles(staged.map((item) => item.temporaryFile));
    throw error;
  }

  const activated: PreparedRuntimeArtifactFile[] = [];
  try {
    for (const item of staged) {
      await rename(item.temporaryFile, item.entry.file);
      activated.push(item.entry);
    }
  } catch (error) {
    const rollbackFailures = await rollbackActivatedFiles(activated);
    throw new RuntimeArtifactCommitError({
      cause: error,
      activatedFiles: activated.map((entry) => entry.destination),
      rollbackFailures,
    });
  } finally {
    await cleanupTemporaryFiles(staged.map((item) => item.temporaryFile));
  }

  return Object.freeze(activated.map((entry) => entry.file));
}

export class RuntimeArtifactCommitError extends Error {
  override readonly name = "RuntimeArtifactCommitError";
  readonly code = "RUNTIME_ARTIFACT_COMMIT_FAILED";
  readonly activatedFiles: readonly string[];
  readonly rollbackFailures: readonly string[];

  constructor(input: {
    readonly cause: unknown;
    readonly activatedFiles: readonly string[];
    readonly rollbackFailures: readonly string[];
  }) {
    const cause = errorMessage(input.cause);
    const activated =
      input.activatedFiles.length === 0
        ? "none"
        : input.activatedFiles.join(", ");
    const rollback =
      input.rollbackFailures.length === 0
        ? "Rollback completed."
        : `Rollback also failed for: ${input.rollbackFailures.join(", ")}.`;
    super(
      `Runtime artifact activation failed: ${cause} Activated before failure: ${activated}. ${rollback}`,
    );
    this.activatedFiles = Object.freeze([...input.activatedFiles]);
    this.rollbackFailures = Object.freeze([...input.rollbackFailures]);
  }
}

async function rollbackActivatedFiles(
  activated: readonly PreparedRuntimeArtifactFile[],
): Promise<readonly string[]> {
  const failures: string[] = [];
  for (const entry of [...activated].reverse()) {
    try {
      const current = await readFile(entry.file, "utf8");
      if (current !== entry.contents) {
        throw new Error("destination changed after activation");
      }
      if (entry.existing === undefined) {
        await rm(entry.file);
      } else {
        const temporaryFile = siblingTemporaryFile(entry.file);
        try {
          await writeFile(temporaryFile, entry.existing, {
            encoding: "utf8",
            flag: "wx",
          });
          await rename(temporaryFile, entry.file);
        } finally {
          await rm(temporaryFile, { force: true });
        }
      }
    } catch (error) {
      failures.push(`${entry.destination}: ${errorMessage(error)}`);
    }
  }
  return Object.freeze(failures);
}

async function assertRealPathSafe(
  rootRealPath: string,
  file: string,
  destination: string,
): Promise<void> {
  let candidate = file;
  for (;;) {
    try {
      const info = await lstat(candidate);
      if (candidate === file && info.isSymbolicLink()) {
        throw unsafeDestination(destination, "destination is a symbolic link");
      }
      const candidateRealPath = await realpath(candidate);
      assertWithinRoot(rootRealPath, candidateRealPath, destination);
      return;
    } catch (error) {
      if (!isNodeError(error) || error.code !== "ENOENT") throw error;
      const parent = dirname(candidate);
      if (parent === candidate) {
        throw unsafeDestination(destination, "no readable parent exists");
      }
      candidate = parent;
    }
  }
}

function assertCanonicalDestination(destination: string): void {
  if (
    destination.length === 0 ||
    destination.includes("\\") ||
    destination.includes("\0") ||
    isAbsolute(destination) ||
    posix.normalize(destination) !== destination ||
    destination === ".." ||
    destination.startsWith("../")
  ) {
    throw unsafeDestination(
      destination,
      "path is not canonical and root-relative",
    );
  }
}

function assertWithinRoot(
  root: string,
  file: string,
  destination: string,
): void {
  const pathFromRoot = relative(root, file);
  if (
    pathFromRoot === ".." ||
    pathFromRoot.startsWith(`..${sep}`) ||
    isAbsolute(pathFromRoot)
  ) {
    throw unsafeDestination(
      destination,
      "path resolves outside the project root",
    );
  }
}

function unsafeDestination(destination: string, reason: string): TypeError {
  return new TypeError(
    `Runtime artifact destination '${destination}' is unsafe: ${reason}.`,
  );
}

async function readExistingFile(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") return undefined;
    throw error;
  }
}

function assertGeneratedFileContentsWritable(
  file: string,
  existing: string | undefined,
  conflictNextStep?: string,
): void {
  if (existing === undefined || isGeneratedRuntimeArtifact(existing)) return;
  throw createRuntimeError({
    code: "ARTIFACTS_STALE",
    whatFailed: `Crux runtime artifact \`${file}\` is not marked as generated.`,
    why: "The generator will not overwrite user-authored files without the Crux generated-file marker.",
    whatStillWorks:
      "Every existing artifact is unchanged. Generation can continue after the path conflict is resolved.",
    nextStep:
      conflictNextStep ??
      "Move or rename the user-authored file, then run `crux runtime generate` again.",
  });
}

function isGeneratedRuntimeArtifact(contents: string): boolean {
  return (
    contents.startsWith(GENERATED_HEADER) ||
    contents.startsWith(LEGACY_GENERATED_HEADER)
  );
}

function siblingTemporaryFile(file: string): string {
  return `${file}.crux-${process.pid}-${randomUUID()}.tmp`;
}

async function cleanupTemporaryFiles(files: readonly string[]): Promise<void> {
  await Promise.all(files.map((file) => rm(file, { force: true })));
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function compareCodepoint(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
