import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { createRuntimeError } from "@use-crux/core/runtime";

export const GENERATED_HEADER = [
  "/*",
  " * This file is generated by Crux. Do not edit.",
  " * It will be overwritten by `crux runtime generate` and `crux dev`.",
  " */",
].join("\n");

const LEGACY_GENERATED_HEADER =
  "/* This file is generated by Crux. Do not edit by hand. */";

/** Write a generated artifact when its canonical contents changed. */
export async function writeGeneratedFile(
  file: string,
  contents: string,
  options: {
    readonly protect?: boolean;
    readonly conflictNextStep?: string;
  } = {},
): Promise<boolean> {
  const existing = await readExistingFile(file);
  if (options.protect)
    assertGeneratedFileContentsWritable(
      file,
      existing,
      options.conflictNextStep,
    );
  if (existing === contents) return false;
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, contents);
  return true;
}

async function readExistingFile(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") return undefined;
    throw error;
  }
}

function assertGeneratedFileContentsWritable(
  file: string,
  existing: string | undefined,
  conflictNextStep?: string,
): void {
  if (existing === undefined || isGeneratedRuntimeArtifact(existing)) return;
  throw createRuntimeError({
    code: "ARTIFACTS_STALE",
    whatFailed: `Crux runtime artifact \`${file}\` is not marked as generated.`,
    why: "The generator will not overwrite user-authored files without the Crux generated-file marker.",
    whatStillWorks:
      "The existing file is unchanged, and other generated artifacts can be regenerated after the path is cleared.",
    nextStep:
      conflictNextStep ??
      "Move or rename the user-authored file, then run `crux runtime generate` again.",
  });
}

function isGeneratedRuntimeArtifact(contents: string): boolean {
  return (
    contents.startsWith(GENERATED_HEADER) ||
    contents.startsWith(LEGACY_GENERATED_HEADER)
  );
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
