import type { PrimitiveEvidenceCoverageDescriptor } from "./types";

/** Renders the committed machine-readable coverage artifact. */
export function renderPrimitiveEvidenceCoverageJson(
  rows: readonly PrimitiveEvidenceCoverageDescriptor[],
): string {
  return `${JSON.stringify({ schemaVersion: 1, rows }, null, 2)}\n`;
}

/** Renders the committed human-readable coverage table. */
export function renderPrimitiveEvidenceCoverageMarkdown(
  rows: readonly PrimitiveEvidenceCoverageDescriptor[],
): string {
  const header = [
    "# Primitive evidence coverage",
    "",
    "> Generated by `pnpm --filter @use-crux/core generate:evidence-coverage`. Do not edit by hand.",
    "",
    "| Primitive | Family | Participation | Native roles | Native status | Runtime | OTel | Interim behavior |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  const body = rows.map((row) => {
    const nativeRoles = Object.entries(row.roles)
      .filter(
        ([, status]) =>
          status === "automatic" ||
          status === "blocked" ||
          status === "native-planned",
      )
      .map(([role, status]) =>
        status === "automatic"
          ? `${role} (automatic)`
          : status === "blocked"
            ? `${role} (blocked)`
            : `${role} (planned)`,
      )
      .join(", ");
    return `| ${cell(row.name)} | ${cell(row.family)} | ${row.participation} | ${cell(nativeRoles || "none")} | ${row.nativeEvidence.status} | ${row.runtimeDurability} | ${row.otelPolicy} | ${cell(row.interimBehavior)} |`;
  });
  return `${[...header, ...body, ""].join("\n")}`;
}

function cell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}
