import { semanticStorageCallNames } from "./storage-model";
import { mediaOperationNames } from "../media/manifest";

const firstPartySemanticCallNames = [
  "Agent",
  "agent",
  "blackboard",
  "cascade",
  "consensus",
  "constraint",
  "convexAgent",
  "createTool",
  "cruxFlow",
  "evaluate",
  "embed",
  "embedMany",
  "embedding",
  "index",
  "indexer",
  "indexDocuments",
  "indexChunks",
  "defer",
  "fallback",
  "flow",
  "fromRegistry",
  "guardrail",
  "injectable",
  "judgeReranker",
  "llmJudge",
  "match",
  "memory",
  "mcp",
  "parallel",
  "pipeline",
  "registry",
  "reindex",
  "compressToBudget",
  "expandParents",
  "fanout",
  "knowledgeBase",
  "rerank",
  "reranker",
  "retrievalRecipe",
  "retrievalStep",
  "retrieve",
  "retriever",
  "rewriteQuery",
  "retry",
  "router",
  "split",
  "swarm",
  "tool",
  "toolPolicy",
  "context",
  "prompt",
  "record",
  "when",
  "workspace",
  ...mediaOperationNames,
  ...semanticStorageCallNames,
] as const;

/** Sorted first-party call names that make a source file semantically relevant. */
export const semanticPrimitiveCallNames = [
  ...new Set(firstPartySemanticCallNames),
].sort();
