/**
 * Durable event port contract.
 *
 * Events are append-only logical facts. Adapters must make an appended event
 * durable before resolving, return cursor-stable reads, and treat duplicate
 * event ids as idempotent. Retryable failures are transient storage failures;
 * invalid JSON payloads must surface as typed runtime diagnostics.
 *
 * @module
 */

import type { JsonValue } from '../../storage'
import type { EventCursor } from './ids'
import type { RuntimePruneOptions, RuntimePruneResult } from './retention'

/** Event input accepted by {@link DurableEventPort.append}. */
export interface NewRuntimeEvent {
  /** Runtime namespace that isolates environments sharing a substrate. */
  readonly namespace: string
  /** Logical event name, including reserved Crux signal names. */
  readonly name: string
  /** Durable JSON payload stored by the event port. */
  readonly payload: JsonValue
  /** Optional caller-provided event id for duplicate append idempotency. */
  readonly eventId?: string
}

/** Durable event returned by append and read operations. */
export interface RuntimeEvent extends NewRuntimeEvent {
  /** Cursor generated by the adapter or durable store. */
  readonly eventId: EventCursor
  /** Time when the event became durable. */
  readonly appendedAt: Date
}

/** Options for appending a durable event. */
export interface AppendEventOptions {
  /** Stable idempotency key when the caller needs duplicate append protection. */
  readonly idempotencyKey?: string
}

/** Cursor read options. */
export interface ReadEventsOptions {
  /** Runtime namespace to read from. */
  readonly namespace: string
  /** Return events after this cursor. Omit to read from the beginning. */
  readonly after?: EventCursor
  /** Maximum number of events to return. */
  readonly limit?: number
}

/** Cursor read result. */
export interface ReadEventsResult {
  /** Events in cursor-stable order. */
  readonly events: readonly RuntimeEvent[]
  /** Cursor for the last returned event, absent when no events were returned. */
  readonly cursor?: EventCursor
  /** Whether the requested `after` cursor is still retained. */
  readonly afterFound?: boolean
}

/** Durable append-only event port. */
export interface DurableEventPort {
  /**
   * Append a durable event.
   *
   * Must be safe under concurrent calls. Duplicate event ids or idempotency keys
   * resolve to the original logical event rather than appending a second fact.
   */
  append(
    event: NewRuntimeEvent,
    options?: AppendEventOptions,
  ): Promise<RuntimeEvent>

  /**
   * Read events after a cursor.
   *
   * Cursors are generated by the adapter. Global ordering is optional, but the
   * order for a namespace must be stable enough for polling and replay.
   */
  read(options: ReadEventsOptions): Promise<ReadEventsResult>

  /**
   * Delete a bounded batch of events appended before the retention cutoff.
   *
   * Event replay reads delivered payloads from snapshots, so retained events
   * are for future waiter matching and diagnostics only.
   */
  prune(options: RuntimePruneOptions): Promise<RuntimePruneResult>
}
