/*
 * This file is generated by Crux. Do not edit.
 * It will be overwritten by `crux runtime generate` and `crux dev`.
 */
import { createRuntimeHandler } from '@use-crux/core/runtime'
import { createDeployedEvalRegistry } from '@use-crux/core/runtime/internal/eval-registry'

const targets = [] as const
export const evalRegistry = createDeployedEvalRegistry({persistencePolicy:{redactPaths:[]},entries:[]})

export const { GET, POST } = createRuntimeHandler({ targets, manifestHash: 'ccedd7af6c59edba70f00bea174b22d7d76d4c5f54e83feebbdef586c81d51d6' })
